robots:
  # - id: 0
  #   ip: "192.168.1.102"   # fill in actual IPs
  #   pub_port: 5550
  #   mocap_rigid_id: 1     # PhaseSpace rigid body ID for this robot
  - id: 1
    ip: "192.168.1.115"
    pub_port: 5550
    mocap_rigid_id: 2
  - id: 0
    ip: "192.168.1.121"
    pub_port: 5557
    mocap_rigid_id: 3
  # - id: 3
  #   ip: "192.168.1.122"
  #   pub_port: 5553
  #   mocap_rigid_id: 4     # PhaseSpace rigid body ID for this robot

laptop:
  ip: "192.168.1.55"     # fill in actual IP
  mocap_pub_port: 5560    # PUB: laptop broadcasts all rigid body poses
  central_pub_port: 5561  # PUB: centralized controller broadcasts cmd_vel

control:
  frequency_hz: 20        # start conservative; increase after validation

payload:
  mocap_rigid_id: 5       # PhaseSpace rigid body ID for the payload

